/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Transformer */

#ifndef _Included_Transformer
#define _Included_Transformer
#ifdef __cplusplus
extern "C" {
#endif
#undef Transformer_SALT
#define Transformer_SALT 35L
/*
 * Class:     Transformer
 * Method:    transform
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_Transformer_transform
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
